name: Feature Request
description: Suggest an idea for the OneGrep TypeScript SDK
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: dropdown
    id: feature_type
    attributes:
      label: Feature Type
      description: What type of feature are you proposing?
      options:
        - General SDK Enhancement
        - New Runtime Support
        - New Provider Support
      default: 0
    validations:
      required: true
  
  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe the use case this feature would enable
      placeholder: |
        Example: As an agent developer, I want to...
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working
      placeholder: |
        Example code or detailed description of the solution:
        ```typescript
        // Your example code here
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions you've considered
      placeholder: |
        Are there other ways to achieve this? Why is this approach better?
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here
      placeholder: |
        Environment details, constraints, or other relevant information
    validations:
      required: false 